# Extension fields for DRY configuration
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

x-health-http: &health_http
  test:
    ["CMD-SHELL", "wget -q --spider $${HEALTH_URL} >/dev/null 2>&1 || exit 1"]
  interval: 30s
  timeout: 10s
  retries: 3
  start_period: 10s

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    logging: *default-logging
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - SESSION_SECRET=${SESSION_SECRET:-dev-secret-key}
      - PORT=${PORT:-3000}
      - CORS_ORIGIN=${CORS_ORIGIN:-*}
      - HEALTH_URL=http://localhost:${PORT:-3000}/health
    volumes:
      - /app/node_modules
      - ./backend:/app
    networks:
      - internal
    healthcheck: *health_http
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - VITE_BACKEND_URL=${VITE_BACKEND_URL:-http://localhost:3000}
      - HEALTH_URL=http://localhost:8080
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - internal
    logging: *default-logging
    healthcheck: *health_http
    restart: unless-stopped

  discord-bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    volumes:
      - ./bot:/app
      - /app/node_modules
    ports:
      - "3001:3001" # Port pour les healthchecks
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging: *default-logging
    environment:
      - NODE_ENV=development
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CLIENT_ID=${DISCORD_CLIENT_ID}
      - API_URL=${VITE_BACKEND_URL:-http://localhost:3000}
      - HEALTH_URL=http://localhost:3001/health
    volumes:
      - /app/node_modules
      - ./bot:/app
      - bot-logs:/app/logs
    command: npm run dev
    networks:
      - internal
    logging: *default-logging
    healthcheck: *health_http
    restart: always
# Root networks/volumes are defined in docker-compose.yml for the local environment.
