version: "3.8"

services:
  fateweaver-postgres:
    image: postgres:15
    container_name: fateweaver-postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-fateweaver}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - POSTGRES_DB=${POSTGRES_DB:-fateweaver}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-fateweaver} -d ${POSTGRES_DB:-fateweaver}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  fateweaver-backend:
    image: ${REGISTRY_URL:-registry.matthias-bouloc.fr}/${IMAGE_NAME:-fateweaver}/backend:${TAG:-latest}
    container_name: fateweaver-backend
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER:-fateweaver}:${POSTGRES_PASSWORD:-changeme}@fateweaver-postgres:5432/${POSTGRES_DB:-fateweaver}?schema=public
    ports:
      - "3000:3000"
    depends_on:
      fateweaver-postgres:
        condition: service_healthy
      fateweaver-prisma-migrate:
        condition: service_completed_successfully
    networks:
      - internal
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - /app/node_modules # Empêche l'écrasement des node_modules par un volume
    restart: unless-stopped

  fateweaver-discord-bot:
    image: ${REGISTRY_URL:-registry.matthias-bouloc.fr}/${IMAGE_NAME:-fateweaver}/bot:${TAG:-latest}
    container_name: fateweaver-discord-bot
    environment:
      - NODE_ENV=production
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_URL=http://fateweaver-backend:3000
    depends_on:
      - fateweaver-backend
    restart: unless-stopped

volumes:
  postgres_data:
