version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: postgres
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-myuser}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-mypass}
      - POSTGRES_DB=${POSTGRES_DB:-mydb}
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - proxy
    ports:
      - "5432:5432"

  backenddev:
    extends:
      file: common.yml
      service: backend
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-myuser}:${POSTGRES_PASSWORD:-mypass}@postgres:5432/${POSTGRES_DB:-mydb}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontenddev:
    extends:
      file: common.yml
      service: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backenddev

  discord-botdev:
    extends:
      file: common.yml
      service: discord-bot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - API_URL=http://backenddev:3000
    depends_on:
      - backenddev
    networks:
      - proxy

networks:
  proxy:
    external: true
